name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:githubdeploy

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 100.66.2.66
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ${{ secrets.SERVER_CWD }}
            git pull
            /root/.bun/bin/bun i --no-save
            /root/.bun/bin/bunx prisma db push
            /root/.bun/bin/bun run build
            supervisorctl restart disaster-intelligence
